#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }


    stage('clean') {
        dir('customerService') {
            sh "pwd"
            sh "ls -a"
            sh "chmod +x mvnw"
            sh "./mvnw clean"
        }

    }

    stage('backend tests') {
        try {
            dir('customerService') {
                sh "./mvnw test"
            }
        } catch (err) {
            throw err
        } finally {
            junit '**/target/surefire-reports/TEST-*.xml'
        }
    }

    stage('package and deploy') {
        dir('customerService') {
            sh "./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy-war -DskipTests -Pprod -Dheroku.appName=bss-customer-svc"
        }
//        archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
    }

}
