#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        dir('customerService') {
            sh "pwd"
            sh "ls -a"
            sh "chmod +x mvnw"
            sh "./mvnw clean"
        }
    }

    stage('backend tests') {
        try {
            dir('customerService') {
                sh "./mvnw test"
            }
        } catch (err) {
            throw err
        } finally {
            junit '**/target/surefire-reports/TEST-*.xml'
        }
    }

    stage('package and deploy') {
        dir('customerService') {
            sh "./mvnw package -Pprod -DskipTests"
            sh "heroku deploy:jar --jar target/*.war --app bss-customer-svc"
        }
    }

}
