#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        dir('customerService') {
            sh "pwd"
            sh "ls -a"
            sh "chmod +x customerService/mvnw"
            sh "./customerService/mvnw clean"
        }

    }

    stage('backend tests') {
        try {
            dir('customerService') {
                sh "cd customerService && ./mvnw test"
            }
        } catch (err) {
            throw err
        } finally {
            junit '**/target/surefire-reports/TEST-*.xml'
        }
    }

    stage('package and deploy') {
        sh "cd customerService && ./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy-war -DskipTests -Pprod -Dheroku.appName="
        archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
    }

}
