#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        dir('customer-service') {
            sh "chmod +x mvnw"
            sh "./mvnw clean"
        }
    }

    stage('backend tests') {
        try {
            dir('customer-service') {
                sh "./mvnw test"
            }
        } catch(err) {
            throw err
        } finally {
            junit '**/target/surefire-reports/TEST-*.xml'
        }
    }

    stage('package and deploy') {
        dir('customer-service') {
            sh "./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy -DskipTests -Pprod -Dheroku.appName=bss-customer-svc"
        }
//        archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
    }

}
